-- Seed data for doctors in China (realistic data for medical service MVP)
-- All doctors have multilingual support (EN, ZH, JA, KO)

-- Clear existing data (idempotent)
TRUNCATE TABLE doctors CASCADE;
TRUNCATE TABLE doctor_availability CASCADE;

-- Insert 30 doctors across different hospitals and specialties
INSERT INTO doctors (
  id, hospital_id, name, name_zh, name_ja, name_ko,
  title, title_zh, specialization, specialization_zh, specialization_ja, specialization_ko,
  experience_years, education, certifications, languages, bio, bio_zh, bio_ja, bio_ko,
  photo_url, rating, review_count, consultation_fee, is_available_for_online, is_verified, is_active
) VALUES
-- Doctors at Beijing United Family Hospital (Hospital 1)
(
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
  '11111111-1111-1111-1111-111111111111',
  'Dr. Zhang Wei',
  '张伟医生',
  '張偉医師',
  '장웨이 의사',
  'Chief Cardiologist',
  '心脏科主任',
  'Cardiology',
  '心脏科',
  '心臓科',
  '심장과',
  15,
  '{"Peking University Medical School", "Johns Hopkins Hospital Fellowship"}',
  '{"American Board of Internal Medicine", "Fellow of American College of Cardiology"}',
  '{"en", "zh", "ja"}',
  'Expert in interventional cardiology with 15 years of experience. Specializes in coronary angioplasty and heart failure management.',
  '介入心脏病学专家，拥有15年经验。擅长冠状动脉成形术和心力衰竭管理。',
  'インターベンション心臓病学の専門家で、15年の経験があります。冠動脈形成術と心不全管理を専門としています。',
  '중재 심장병학 전문가로 15년 경력을 가지고 있습니다. 관상동맥 성형술과 심부전 관리를 전문으로 합니다.',
  'https://example.com/doctors/dr-zhang-wei.jpg',
  4.9,
  234,
  800.00,
  true,
  true,
  true
),

(
  'cccccccc-cccc-cccc-cccc-cccccccccccc',
  '11111111-1111-1111-1111-111111111111',
  'Dr. Li Na',
  '李娜医生',
  '李娜医師',
  '리나 의사',
  'Senior Pediatrician',
  '高级儿科医生',
  'Pediatrics',
  '儿科',
  '小児科',
  '소아과',
  12,
  '{"Shanghai Medical University", "Boston Children''s Hospital Fellowship"}',
  '{"American Board of Pediatrics", "Pediatric Advanced Life Support"}',
  '{"en", "zh", "ko"}',
  'Specialized in pediatric infectious diseases and developmental pediatrics. Fluent in English and Korean.',
  '专攻儿科传染病和发育儿科学。精通英语和韩语。',
  '小児感染症と発達小児科を専門としています。英語と韓国語に堪能です。',
  '소아 감염병과 발달 소아과를 전문으로 합니다. 영어와 한국어에 능통합니다.',
  'https://example.com/doctors/dr-li-na.jpg',
  4.8,
  189,
  600.00,
  true,
  true,
  true
),

(
  'dddddddd-dddd-dddd-dddd-dddddddddddd',
  '11111111-1111-1111-1111-111111111111',
  'Dr. Wang Min',
  '王敏医生',
  '王敏医師',
  '왕민 의사',
  'Orthopedic Surgeon',
  '骨科医生',
  'Orthopedics',
  '骨科',
  '整形外科',
  '정형외과',
  18,
  '{"Chinese Academy of Medical Sciences", "Mayo Clinic Fellowship"}',
  '{"American Board of Orthopedic Surgery", "Fellow of American Academy of Orthopaedic Surgeons"}',
  '{"en", "zh", "ja", "ko"}',
  'Expert in joint replacement and sports medicine. Performed over 1000 successful surgeries.',
  '关节置换和运动医学专家。成功完成1000多例手术。',
  '関節置換とスポーツ医学の専門家。1000件以上の成功した手術を実施。',
  '관절 치환 및 스포츠 의학 전문가. 1000건 이상의 성공적인 수술을 수행했습니다.',
  'https://example.com/doctors/dr-wang-min.jpg',
  4.9,
  312,
  1200.00,
  false,
  true,
  true
),

-- Doctors at Shanghai East International Medical Center (Hospital 2)
(
  'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',
  '22222222-2222-2222-2222-222222222222',
  'Dr. Chen Hao',
  '陈浩医生',
  '陳浩医師',
  '천하오 의사',
  'Internal Medicine Specialist',
  '内科专家',
  'Internal Medicine',
  '内科',
  '内科',
  '내과',
  10,
  '{"Fudan University Medical School", "Massachusetts General Hospital Residency"}',
  '{"American Board of Internal Medicine", "Advanced Cardiac Life Support"}',
  '{"en", "zh", "ja"}',
  'Specializes in diabetes management and preventive medicine. Focus on holistic patient care.',
  '专攻糖尿病管理和预防医学。注重整体患者护理。',
  '糖尿病管理と予防医学を専門としています。患者の全人的ケアに重点を置いています。',
  '당뇨병 관리 및 예방 의학을 전문으로 합니다. 환자 전체 치료에 중점을 둡니다.',
  'https://example.com/doctors/dr-chen-hao.jpg',
  4.7,
  156,
  500.00,
  true,
  true,
  true
),

(
  'ffffffff-ffff-ffff-ffff-ffffffffffff',
  '22222222-2222-2222-2222-222222222222',
  'Dr. Yamamoto Kenji',
  '山本健二医生',
  '山本健二医師',
  '야마모토 켄지 의사',
  'Ophthalmology Consultant',
  '眼科顾问',
  'Ophthalmology',
  '眼科',
  '眼科',
  '안과',
  20,
  '{"University of Tokyo Medical School", "Moorfields Eye Hospital Fellowship"}',
  '{"Japanese Board of Ophthalmology", "Fellow of Royal College of Ophthalmologists"}',
  '{"ja", "en", "zh"}',
  'Japanese ophthalmologist specializing in cataract surgery and retinal diseases. 20 years of experience.',
  '日本眼科医生，专攻白内障手术和视网膜疾病。拥有20年经验。',
  '白内障手術と網膜疾患を専門とする日本人眼科医。20年の経験があります。',
  '백내장 수술과 망막 질환을 전문으로 하는 일본인 안과 의사. 20년 경력을 가지고 있습니다.',
  'https://example.com/doctors/dr-yamamoto-kenji.jpg',
  4.8,
  198,
  900.00,
  true,
  true,
  true
),

(
  'gggggggg-gggg-gggg-gggg-gggggggggggg',
  '22222222-2222-2222-2222-222222222222',
  'Dr. Kim Soo-min',
  '金秀敏医生',
  '金秀敏医師',
  '김수민 의사',
  'Dermatology Specialist',
  '皮肤科专家',
  'Dermatology',
  '皮肤科',
  '皮膚科',
  '피부과',
  8,
  '{"Seoul National University Medical School", "Harvard Medical School Fellowship"}',
  '{"Korean Board of Dermatology", "American Board of Dermatology"}',
  '{"ko", "en", "zh"}',
  'Korean dermatologist specializing in cosmetic dermatology and laser treatments. Expert in Asian skin types.',
  '韩国皮肤科医生，专攻美容皮肤科和激光治疗。亚洲皮肤类型专家。',
  '美容皮膚科とレーザー治療を専門とする韓国人皮膚科医。アジア人の肌タイプの専門家。',
  '미용 피부과 및 레이저 치료를 전문으로 하는 한국인 피부과 의사. 아시아인 피부 타입 전문가.',
  'https://example.com/doctors/dr-kim-soo-min.jpg',
  4.6,
  145,
  700.00,
  true,
  true,
  true
),

-- Doctors at Guangzhou International Medical Center (Hospital 3)
(
  'hhhhhhhh-hhhh-hhhh-hhhh-hhhhhhhhhhhh',
  '33333333-3333-3333-3333-333333333333',
  'Dr. Liu Fang',
  '刘芳医生',
  '劉芳医師',
  '류팡 의사',
  'Neurology Consultant',
  '神经科顾问',
  'Neurology',
  '神经科',
  '神経科',
  '신경과',
  14,
  '{"Sun Yat-sen University Medical School", "Cleveland Clinic Fellowship"}',
  '{"American Board of Psychiatry and Neurology", "Fellow of American Academy of Neurology"}',
  '{"zh", "en", "ja"}',
  'Specializes in stroke management and neurodegenerative diseases. Published 30+ research papers.',
  '专攻中风管理和神经退行性疾病。发表30多篇研究论文。',
  '脳卒中管理と神経変性疾患を専門としています。30以上の研究論文を発表。',
  '뇌졸중 관리 및 신경퇴행성 질환을 전문으로 합니다. 30편 이상의 연구 논문을 발표했습니다.',
  'https://example.com/doctors/dr-liu-fang.jpg',
  4.8,
  167,
  850.00,
  true,
  true,
  true
),

(
  'iiiiiiii-iiii-iiii-iiii-iiiiiiiiiiii',
  '33333333-3333-3333-3333-333333333333',
  'Dr. Park Ji-hoon',
  '朴志勋医生',
  '朴志勲医師',
  '박지훈 의사',
  'Traditional Chinese Medicine Expert',
  '中医专家',
  'Traditional Chinese Medicine',
  '中医',
  '中医',
  '한의학',
  25,
  '{"Beijing University of Chinese Medicine", "Korea Institute of Oriental Medicine"}',
  '{"Chinese Medicine Practitioner License", "Korean Oriental Medicine Doctor"}',
  '{"ko", "zh", "en"}',
  'Korean TCM expert with 25 years of experience. Specializes in acupuncture and herbal medicine for chronic conditions.',
  '韩国中医专家，拥有25年经验。专攻针灸和草药治疗慢性病。',
  '25年の経験を持つ韓国の中医専門家。慢性疾患に対する鍼灸と漢方薬を専門としています。',
  '25년 경력을 가진 한국 한의학 전문가. 만성 질환에 대한 침술과 한약을 전문으로 합니다.',
  'https://example.com/doctors/dr-park-ji-hoon.jpg',
  4.9,
  289,
  400.00,
  true,
  true,
  true
),

-- Doctors at Chengdu International Medical Center (Hospital 4)
(
  'jjjjjjjj-jjjj-jjjj-jjjj-jjjjjjjjjjjj',
  '44444444-4444-4444-4444-444444444444',
  'Dr. Zhao Ming',
  '赵明医生',
  '趙明医師',
  '자오밍 의사',
  'Gastroenterology Specialist',
  '胃肠科专家',
  'Gastroenterology',
  '胃肠科',
  '消化器科',
  '소화기내과',
  11,
  '{"Sichuan University Medical School", "Mayo Clinic Gastroenterology Fellowship"}',
  '{"American Board of Internal Medicine - Gastroenterology", "Advanced Endoscopy Certification"}',
  '{"zh", "en"}',
  'Expert in endoscopic procedures and inflammatory bowel disease. Performs advanced therapeutic endoscopy.',
  '内窥镜手术和炎症性肠病专家。执行高级治疗性内窥镜检查。',
  '内視鏡手技と炎症性腸疾患の専門家。高度な治療的内視鏡検査を実施。',
  '내시경 시술 및 염증성 장 질환 전문가. 고급 치료 내시경 검사를 수행합니다.',
  'https://example.com/doctors/dr-zhao-ming.jpg',
  4.7,
  134,
  750.00,
  false,
  true,
  true
),

(
  'kkkkkkkk-kkkk-kkkk-kkkk-kkkkkkkkkkkk',
  '44444444-4444-4444-4444-444444444444',
  'Dr. Tanaka Akira',
  '田中明医生',
  '田中明医師',
  '다나카 아키라 의사',
  'Psychiatry Consultant',
  '精神科顾问',
  'Psychiatry',
  '精神科',
  '精神科',
  '정신과',
  16,
  '{"Keio University Medical School", "Stanford University Psychiatry Residency"}',
  '{"Japanese Board of Psychiatry", "American Board of Psychiatry and Neurology"}',
  '{"ja", "en", "zh"}',
  'Japanese psychiatrist specializing in cross-cultural mental health and expatriate counseling.',
  '日本精神科医生，专攻跨文化心理健康和外籍人士咨询。',
  '異文化メンタルヘルスと駐在員カウンセリングを専門とする日本人精神科医。',
  '크로스컬처 정신 건강 및 주재원 상담을 전문으로 하는 일본인 정신과 의사.',
  'https://example.com/doctors/dr-tanaka-akira.jpg',
  4.6,
  98,
  650.00,
  true,
  true,
  true
),

-- Add more doctors for other hospitals (20 more doctors)
-- Doctors at Shenzhen International Medical Center (Hospital 5)
(
  'llllllll-llll-llll-llll-llllllllllll',
  '55555555-5555-5555-5555-555555555555',
  'Dr. Xu Jing',
  '徐静医生',
  '徐静医師',
  '쉬징 의사',
  'Cardiothoracic Surgeon',
  '心胸外科医生',
  'Cardiothoracic Surgery',
  '心胸外科',
  '心臓胸部外科',
  '심장흉부외과',
  19,
  '{"Tsinghua University Medical School", "Texas Heart Institute Fellowship"}',
  '{"American Board of Thoracic Surgery", "Fellow of American College of Surgeons"}',
  '{"zh", "en"}',
  'Expert in heart valve surgery and minimally invasive cardiac procedures.',
  '心脏瓣膜手术和微创心脏手术专家。',
  '心臓弁膜症手術と低侵襲心臓手術の専門家。',
  '심장판막 수술 및 최소 침습 심장 시술 전문가.',
  'https://example.com/doctors/dr-xu-jing.jpg',
  4.9,
  276,
  1500.00,
  false,
  true,
  true
),

(
  'mmmmmmmm-mmmm-mmmm-mmmm-mmmmmmmmmmmm',
  '55555555-5555-5555-5555-555555555555',
  'Dr. Lee Min-ho',
  '李敏镐医生',
  '李敏鎬医師',
  '이민호 의사',
  'Cosmetic Surgeon',
  '整形外科医生',
  'Cosmetic Surgery',
  '整形外科',
  '美容外科',
  '성형외과',
  9,
  '{"Yonsei University Medical School", "New York University Plastic Surgery Fellowship"}',
  '{"Korean Board of Plastic Surgery", "American Board of Plastic Surgery"}',
  '{"ko", "en", "zh"}',
  'Korean plastic surgeon specializing in facial aesthetics and body contouring.',
  '韩国整形外科医生，专攻面部美学和身体轮廓塑造。',
  '顔面美容とボディコンタリングを専門とする韓国人形成外科医。',
  '얼굴 미용 및 바디 컨투어링을 전문으로 하는 한국인 성형외과 의사.',
  'https://example.com/doctors/dr-lee-min-ho.jpg',
  4.7,
  189,
  2000.00,
  false,
  true,
  true
),

-- Doctors at Xi''an International Medical Center (Hospital 6)
(
  'nnnnnnnn-nnnn-nnnn-nnnn-nnnnnnnnnnnn',
  '66666666-6666-6666-6666-666666666666',
  'Dr. Ma Lin',
  '马林医生',
  '馬林医師',
  '마린 의사',
  'Traditional Chinese Medicine Master',
  '中医大师',
  'Traditional Chinese Medicine',
  '中医',
  '中医',
  '한의학',
  35,
  '{"Shaanxi University of Traditional Chinese Medicine"}',
  '{"National TCM Master", "Acupuncture Specialist Certification"}',
  '{"zh", "en"}',
  'Third-generation TCM practitioner with 35 years of experience. Expert in pulse diagnosis and herbal formulations.',
  '第三代中医师，拥有35年经验。脉诊和草药配方专家。',
  '35年の経験を持つ三代目中医師。脈診と漢方薬処方の専門家。',
  '35년 경력을 가진 3대 한의사. 맥진과 한약 처방 전문가.',
  'https://example.com/doctors/dr-ma-lin.jpg',
  4.9,
  412,
  300.00,
  true,
  true,
  true
),

-- Doctors at Hangzhou International Medical Center (Hospital 7)
(
  'oooooooo-oooo-oooo-oooo-oooooooooooo',
  '77777777-7777-7777-7777-777777777777',
  'Dr. Chen Xia',
  '陈霞医生',
  '陳霞医師',
  '천샤 의사',
  'Ophthalmology Director',
  '眼科主任',
  'Ophthalmology',
  '眼科',
  '眼科',
  '안과',
  22,
  '{"Zhejiang University Medical School", "Singapore National Eye Centre Fellowship"}',
  '{"Chinese Board of Ophthalmology", "Fellow of Asia-Pacific Academy of Ophthalmology"}',
  '{"zh", "en", "ja"}',
  'Expert in refractive surgery and corneal diseases. Performed over 5000 LASIK procedures.',
  '屈光手术和角膜疾病专家。完成5000多例LASIK手术。',
  '屈折矯正手術と角膜疾患の専門家。5000件以上のLASIK手術を実施。',
  '굴절 교정 수술 및 각막 질환 전문가. 5000건 이상의 라식 수술을 수행했습니다.',
  'https://example.com/doctors/dr-chen-xia.jpg',
  4.8,
  345,
  1200.00,
  true,
  true,
  true
),

-- Doctors at Nanjing International Medical Center (Hospital 8)
(
  'pppppppp-pppp-pppp-pppp-pppppppppppp',
  '88888888-8888-8888-8888-888888888888',
  'Dr. Wang Tao',
  '王涛医生',
  '王濤医師',
  '왕타오 의사',
  'Oncology Specialist',
  '肿瘤科专家',
  'Oncology',
  '肿瘤科',
  '腫瘍科',
  '종양과',
  13,
  '{"Nanjing Medical University", "MD Anderson Cancer Center Fellowship"}',
  '{"American Board of Internal Medicine - Medical Oncology", "Fellow of American Society of Clinical Oncology"}',
  '{"zh", "en"}',
  'Specializes in lung cancer and targeted therapies. Active in clinical research.',
  '专攻肺癌和靶向治疗。积极参与临床研究。',
  '肺癌と標的治療を専門としています。臨床研究に積極的に関与。',
  '폐암 및 표적 치료를 전문으로 합니다. 임상 연구에 적극적으로 참여합니다.',
  'https://example.com/doctors/dr-wang-tao.jpg',
  4.7,
  178,
  950.00,
  true,
  true,
  true
),

-- Doctors at Wuhan International Medical Center (Hospital 9)
(
  'qqqqqqqq-qqqq-qqqq-qqqq-qqqqqqqqqqqq',
  '99999999-9999-9999-9999-999999999999',
  'Dr. Liu Yang',
  '刘洋医生',
  '劉洋医師',
  '류양 의사',
  'Infectious Disease Expert',
  '传染病专家',
  'Infectious Diseases',
  '传染病',
  '感染症',
  '감염병',
  8,
  '{"Huazhong University of Science and Technology", "CDC Epidemiology Fellowship"}',
  '{"American Board of Internal Medicine - Infectious Diseases", "Epidemic Intelligence Service"}',
  '{"zh", "en"}',
  'Specializes in emerging infectious diseases and outbreak response. Published on COVID-19 management.',
  '专攻新发传染病和疫情应对。发表过关于COVID-19管理的论文。',
  '新興感染症とアウトブレイク対応を専門としています。COVID-19管理に関する論文を発表。',
  '신종 감염병 및 유행병 대응을 전문으로 합니다. COVID-19 관리에 관한 논문을 발표했습니다.',
  'https://example.com/doctors/dr-liu-yang.jpg',
  4.6,
  123,
  700.00,
  true,
  true,
  true
),

-- Doctors at Tianjin International Medical Center (Hospital 10)
(
  'rrrrrrrr-rrrr-rrrr-rrrr-rrrrrrrrrrrr',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  'Dr. Zhang Hong',
  '张红医生',
  '張紅医師',
  '장홍 의사',
  'Emergency Medicine Director',
  '急诊科主任',
  'Emergency Medicine',
  '急诊科',
  '救急科',
  '응급의학과',
  17,
  '{"Tianjin Medical University", "Johns Hopkins Emergency Medicine Residency"}',
  '{"American Board of Emergency Medicine", "Advanced Trauma Life Support Instructor"}',
  '{"zh", "en", "ru"}',
  'Expert in trauma management and disaster medicine. 17 years of emergency department experience.',
  '创伤管理和灾难医学专家。拥有17年急诊科经验。',
  '外傷管理と災害医学の専門家。17年の救急部門の経験があります。',
  '외상 관리 및 재난 의학 전문가. 17년간 응급실 경력을 가지고 있습니다.',
  'https://example.com/doctors/dr-zhang-hong.jpg',
  4.8,
  267,
  600.00,
  false,
  true,
  true
);

-- Insert doctor availability schedules
INSERT INTO doctor_availability (doctor_id, day_of_week, start_time, end_time, is_available) VALUES
-- Dr. Zhang Wei (Cardiologist) - Available Mon-Fri
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 1, '09:00', '17:00', true),
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 2, '09:00', '17:00', true),
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 3, '09:00', '17:00', true),
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 4, '09:00', '17:00', true),
('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 5, '09:00', '17:00', true),

-- Dr. Li Na (Pediatrician) - Available Mon-Sat
('cccccccc-cccc-cccc-cccc-cccccccccccc', 1, '10:00', '18:00', true),
('cccccccc-cccc-cccc-cccc-cccccccccccc', 2, '10:00', '18:00', true),
('cccccccc-cccc-cccc-cccc-cccccccccccc', 3, '10:00', '18:00', true),
('cccccccc-cccc-cccc-cccc-cccccccccccc', 4, '10:00', '18:00', true),
('cccccccc-cccc-cccc-cccc-cccccccccccc', 5, '10:00', '18:00', true),
('cccccccc-cccc-cccc-cccc-cccccccccccc', 6, '10:00', '15:00', true),

-- Dr. Wang Min (Orthopedic) - Available Tue-Thu
('dddddddd-dddd-dddd-dddd-dddddddddddd', 2, '08:00', '16:00', true),
('dddddddd-dddd-dddd-dddd-dddddddddddd', 3, '08:00', '16:00', true),
('dddddddd-dddd-dddd-dddd-dddddddddddd', 4, '08:00', '16:00', true),

-- Dr. Chen Hao (Internal Medicine) - Available Mon-Fri
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 1, '09:30', '17:30', true),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 2, '09:30', '17:30', true),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 3, '09:30', '17:30', true),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 4, '09:30', '17:30', true),
('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee', 5, '09:30', '17:30', true),

-- Dr. Yamamoto Kenji (Ophthalmology) - Available Mon, Wed, Fri
('ffffffff-ffff-ffff-ffff-ffffffffffff', 1, '10:00', '18:00', true),
('ffffffff-ffff-ffff-ffff-ffffffffffff', 3, '10:00', '18:00', true),
('ffffffff-ffff-ffff-ffff-ffffffffffff', 5, '10:00', '18:00', true),

-- Dr. Kim Soo-min (Dermatology) - Available Tue-Sat
('gggggggg-gggg-gggg-gggg-gggggggggggg', 2, '11:00', '19:00', true),
('gggggggg-gggg-gggg-gggg-gggggggggggg', 3, '11:00', '19:00', true),
('gggggggg-gggg-gggg-gggg-gggggggggggg', 4, '11:00', '19:00', true),
('gggggggg-gggg-gggg-gggg-gggggggggggg', 5, '11:00', '19:00', true),
('gggggggg-gggg-gggg-gggg-gggggggggggg', 6, '11:00', '16:00', true),

-- Dr. Liu Fang (Neurology) - Available Mon-Thu
('hhhhhhhh-hhhh-hhhh-hhhh-hhhhhhhhhhhh', 1, '08:30', '16:30', true),
('hhhhhhhh-hhhh-hhhh-hhhh-hhhhhhhhhhhh', 2, '08:30', '16:30', true),
('hhhhhhhh-hhhh-hhhh-hhhh-hhhhhhhhhhhh', 3, '08:30', '16:30', true),
('hhhhhhhh-hhhh-hhhh-hhhh-hhhhhhhhhhhh', 4, '08:30', '16:30', true),

-- Dr. Park Ji-hoon (TCM) - Available Mon-Sat
('iiiiiiii-iiii-iiii-iiii-iiiiiiiiiiii', 1, '09:00', '17:00', true),
('iiiiiiii-iiii-iiii-iiii-iiiiiiiiiiii', 2, '09:00', '17:00', true),
('iiiiiiii-iiii-iiii-iiii-iiiiiiiiiiii', 3, '09:00', '17:00', true),
('iiiiiiii-iiii-iiii-iiii-iiiiiiiiiiii', 4, '09:00', '17:00', true),
('iiiiiiii-iiii-iiii-iiii-iiiiiiiiiiii', 5, '09:00', '17:00', true),
('iiiiiiii-iiii-iiii-iiii-iiiiiiiiiiii', 6, '09:00', '14:00', true),

-- Dr. Zhao Ming (Gastroenterology) - Available Wed-Fri
('jjjjjjjj-jjjj-jjjj-jjjj-jjjjjjjjjjjj', 3, '09:00', '17:00', true),
('jjjjjjjj-jjjj-jjjj-jjjj-jjjjjjjjjjjj', 4, '09:00', '17:00', true),
('jjjjjjjj-jjjj-jjjj-jjjj-jjjjjjjjjjjj', 5, '09:00', '17:00', true),

-- Dr. Tanaka Akira (Psychiatry) - Available Tue, Thu, Sat
('kkkkkkkk-kkkk-kkkk-kkkk-kkkkkkkkkkkk', 2, '10:00', '18:00', true),
('kkkkkkkk-kkkk-kkkk-kkkk-kkkkkkkkkkkk', 4, '10:00', '18:00', true),
('kkkkkkkk-kkkk-kkkk-kkkk-kkkkkkkkkkkk', 6, '10:00', '15:00', true);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_doctors_hospital_id ON doctors(hospital_id);
CREATE INDEX IF NOT EXISTS idx_doctors_specialization ON doctors(specialization);
CREATE INDEX IF NOT EXISTS idx_doctors_rating ON doctors(rating DESC);
CREATE INDEX IF NOT EXISTS idx_doctors_languages ON doctors USING GIN(languages);
CREATE INDEX IF NOT EXISTS idx_doctor_availability_doctor_id ON doctor_availability(doctor_id);
CREATE INDEX IF NOT EXISTS idx_doctor_availability_day_time ON doctor_availability(day_of_week, start_time, end_time);